
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
 
