services:
  - type: web
    name: message-logger-frontend
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://message-logger-9qkf.onrender.com